- id: hadolint
  name: hadolint
  description: Haskell-based Docker image linter
  language: docker_image
  types:
  - dockerfile
  entry: --entrypoint /bin/hadolint hadolint/hadolint:v1.17.5-8-gc8bf307-alpine -
