- id: hadolint
  name: hadolint
  description: Haskell-based Docker image linter
  language: docker_image
  types:
  - dockerfile
  entry: --entrypoint /bin/hadolint hadolint/hadolint:v1.19.0-44-gf364c91-alpine -
